// gen_handles_fixture.mjs -- writes tests/handles_fixture.hpp from the handle
// model (playground/handles-model.js), the spec of the Kinetic² renderer.
// Run from the Kinetic root after any change to the model or these cases:
//   node tests/gen_handles_fixture.mjs
// Constraints:
// - Positions and ceilings are written in window units (mm / window width),
//   the kernel's units; times in integer milliseconds on the author's clock.
// - The 1 ms grid inverts t(u) by bisection: u is the curve parameter, never time.
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const M = createRequire(import.meta.url)(join(here, '..', 'playground', 'handles-model.js'));

const FIG = [{ at: 0, pos: 0 }, { at: 200, pos: 100 }, { at: 400, pos: 0 }, { at: 600, pos: 100 }, { at: 800, pos: 0 }];
const CASES = [
  { name: 'sample', cfg: {}, doc: M.SAMPLE },
  { name: 'figure', cfg: { vmax: 1000, amax: 50000, jmax: 5e6, lo: 0, hi: 150 }, doc: { actions: FIG } },
  // the trim paths: the model's own trim case, and the figure over its ceilings ending on a hold
  { name: 'sample_trim', cfg: { vmax: 800 }, doc: M.SAMPLE },
  { name: 'figure_tight', cfg: { vmax: 600, amax: 20000, jmax: 5e6, lo: 0, hi: 150 }, doc: { actions: [...FIG, { at: 1000, pos: 0 }] } },
];

// position of one rendered piece at absolute time t (s)
function positionAt(L, R, t) {
  const pL = M.pos(L) + L.dp, pR = M.pos(R) + R.dp, T = R.t - L.t, D = pR - pL;
  const P = [[0, 0], [L.effOut * T, L.vOut * L.effOut * T], [T - R.effIn * T, D - R.vIn * R.effIn * T], [T, D]];
  const bz = (u, c) => { const w = 1 - u; return w * w * w * P[0][c] + 3 * u * w * w * P[1][c] + 3 * u * u * w * P[2][c] + u * u * u * P[3][c]; };
  let lo = 0, hi = 1;
  const tt = t - L.t;
  for (let n = 0; n < 60; n++) { const m = (lo + hi) / 2; if (bz(m, 0) < tt) lo = m; else hi = m; }
  return pL + bz((lo + hi) / 2, 1);
}

const f = (x) => (Object.is(x, -0) ? 0 : x).toPrecision(9).replace(/\.?0+$/, '').replace(/\.?0+e/, 'e');
const list = (a) => a.map(f).join(', ');
let out = '// handles_fixture.hpp -- generated by tests/gen_handles_fixture.mjs from\n';
out += '// playground/handles-model.js; do not edit. Regenerate from the Kinetic root:\n';
out += '//   node tests/gen_handles_fixture.mjs\n';
out += '#pragma once\n\nnamespace handles_fixture {\n\n';
out += 'struct Case {\n    const char* name;\n    float vmax, amax, jmax;          // window units\n';
out += '    int n;                           // knots\n    const unsigned* t_ms;            // authored times\n';
out += '    const float* p;                  // authored positions\n    const float* dp;                 // the model\'s trims\n';
out += '    const unsigned char* infeasible; // the incoming piece is over a ceiling after the whole trim\n';
out += '    int n_ms;                        // samples, t = 0..n_ms-1 ms\n    const float* ms_p;               // the model\'s position every 1 ms\n};\n\n';
const rows = [];
for (const cs of CASES) {
  const c = { ...M.DEF, ...cs.cfg }, W = c.hi - c.lo;
  const knots = M.fromFunscript(cs.doc, cs.cfg);
  M.render(knots, cs.cfg);
  const id = cs.name.replace(/(^|_)(\w)/g, (_, __, ch) => ch.toUpperCase());
  const last = Math.round(knots[knots.length - 1].t * 1000);
  const ms = [];
  for (let t = 0, i = 0; t <= last; t++) {
    while (i < knots.length - 2 && knots[i + 1].t * 1000 <= t) i++;
    ms.push((positionAt(knots[i], knots[i + 1], t / 1000) - c.lo) / W);
  }
  out += `static const unsigned k${id}T[] = { ${knots.map((k) => Math.round(k.t * 1000)).join(', ')} };\n`;
  out += `static const float k${id}P[] = { ${list(knots.map((k) => (M.pos(k) - c.lo) / W))} };\n`;
  out += `static const float k${id}Dp[] = { ${list(knots.map((k) => k.dp / W))} };\n`;
  out += `static const unsigned char k${id}Infeasible[] = { ${knots.map((k) => (k.infeasible ? 1 : 0)).join(', ')} };\n`;
  out += `static const float k${id}Ms[] = {\n`;
  for (let i = 0; i < ms.length; i += 10) out += `    ${list(ms.slice(i, i + 10))},\n`;
  out += '};\n\n';
  rows.push(`    { "${cs.name}", ${f(c.vmax / W)}, ${f(c.amax / W)}, ${f(c.jmax / W)}, ${knots.length}, k${id}T, k${id}P, k${id}Dp, k${id}Infeasible, ${ms.length}, k${id}Ms },`);
}
out += `static const Case kCases[] = {\n${rows.join('\n')}\n};\n\n}  // namespace handles_fixture\n`;
writeFileSync(join(here, 'handles_fixture.hpp'), out);
console.log(`wrote tests/handles_fixture.hpp (${CASES.length} cases)`);
